name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Copy to FMM Finance Dashboard (master branch)
        if: github.ref_name == 'master'
        run: |
          xcopy "${{ github.workspace }}" "C:\inetpub\wwwroot\new-dashboard\new-dashboard-frontend" /E /H /C /I /Y

      - run: echo "🍏 This job's status is ${{ job.status }}."