name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: 
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env: 
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

      - name: Deploy to FMM Finance Dashboard (IIS)
        run: |
          xcopy "${{ github.workspace }}" "C:\inetpub\wwwroot\new-dashboard\new-dashboard-frontend" /E /H /C /I /Y

      - run: echo "🍏 Deployment status is ${{ job.status }}."